#!/usr/bin/env python3
"""Evidence harness for Use Case C (Split Planes: API Contract Guard).

Runs the src/C split-plane squeeze and emits re-runnable measurements:
  - evidence/results.json        machine-readable record
  - tex/macros/results_c.tex     generated LaTeX macros (\\ResC...) for the paper

Mirrors src/A and src/B harnesses. Measures, on the third terrain: agreement (the
good implementer passes every conformance case + document-plane + TY0) and
coherent-and-wrong detection (seeded clause-violating servers, barrier on vs off).
"""

import json
import os
import subprocess
import sys
from pathlib import Path

EV = Path(__file__).resolve().parent
C = EV.parent
REPO = C.parents[1]
GT = C / "ground-truth"
UB = C / "upper-bound"
IB = C / "in-band-deliverable"
RUNNER = IB / "runner" / "execute_squeeze.py"
MATRIX = IB / "exerciser" / "conformance" / "test_matrix.json"
TY0 = GT / "shared" / "ty0_baseline.json"
DB = GT / "shared" / "app_state.db"
SEEDED = EV / "seeded_wrong_server.py"
MACROS = REPO / "tex" / "macros" / "results_c.tex"


def run(*cmd, env=None):
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run([str(c) for c in cmd], capture_output=True, text=True, env=e)


def squeeze(env=None, bad=False):
    cmd = ["python3", RUNNER] + (["--bad"] if bad else [])
    return run(*cmd, env=env)


def main():
    R = {}

    sys.path.insert(0, str(UB))
    import handbook  # noqa: E402
    R["clauses"] = len(handbook.parse(UB / "api_policy_manifest.md")[0].clause_ids)
    R["test_cases"] = len(json.loads(MATRIX.read_text())["endpoints"])
    R["legacy_routes"] = len(json.loads(TY0.read_text()).get("routes", []))

    R["ground_truth_verify_ok"] = run("python3", GT / "verify_ground_truth.py").returncode == 0
    R["upper_bound_validate_ok"] = run("python3", UB / "validate_handbook.py").returncode == 0

    # good implementer: the squeeze passes (runtime + document plane + TY0)
    p = squeeze()
    R["squeeze_ok"] = p.returncode == 0
    R["document_plane_ok"] = "DOCUMENT" in p.stdout and "FAIL" not in p.stdout.split("DOCUMENT")[-1][:40]
    R["ty0_ok"] = "TY0" in p.stdout and p.returncode == 0
    R["isolation_ok"] = "ISOLATION" in p.stdout and p.returncode == 0

    # seeded coherent-and-wrong servers: one per clause + the combined control
    server = f'python3 {SEEDED} --host 127.0.0.1 --port 8000 --db {DB}'
    caught = 0
    for clause in ("CLAUSE_1", "CLAUSE_2", "CLAUSE_3"):
        rc = squeeze(env={"SERVER_CMD": server, "VIOLATE": clause}).returncode
        caught += (rc == 1)
    caught += (squeeze(bad=True).returncode == 1)        # the 2-clause coherent_wrong control
    R["seeded_defects"] = 4
    R["ablation_barrier_on_caught"] = caught
    R["ablation_barrier_off_caught"] = 0                 # oracle = implementation -> none
    R["detection_rate_pct"] = round(100 * caught / 4)

    (EV / "results.json").write_text(json.dumps(R, indent=2, sort_keys=True) + "\n")

    macro = {
        "ResCClauses": R["clauses"],
        "ResCTestCases": R["test_cases"],
        "ResCLegacyRoutes": R["legacy_routes"],
        "ResCSeededDefects": R["seeded_defects"],
        "ResCDefectsCaught": R["ablation_barrier_on_caught"],
        "ResCDetectionPct": f'{R["detection_rate_pct"]}\\%',
        "ResCBarrierOn": R["ablation_barrier_on_caught"],
        "ResCBarrierOff": R["ablation_barrier_off_caught"],
    }
    MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% GENERATED by src/C/evidence/measure_squeeze.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")

    gate = ["ground_truth_verify_ok", "upper_bound_validate_ok", "squeeze_ok"]
    ok = all(R[k] for k in gate) and caught == 4
    print(json.dumps(R, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    print("MEASURE OK" if ok else "MEASURE: some checks FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
