#!/usr/bin/env python3
"""Evidence harness for Use Case B (Authored Authority: refund bot).

Runs the src/B squeeze end-to-end and emits re-runnable measurements:
  - evidence/results.json        machine-readable record
  - tex/macros/results_b.tex     generated LaTeX macros (\\ResB...) for the paper

Mirrors src/A/evidence/measure_squeeze.py. Measures, on a second terrain:
agreement (the good bot passes every scenario + archive regression) and
coherent-and-wrong detection (seeded clause-violating bots, with the physical
barrier on vs off).
"""

import json
import subprocess
import sys
from pathlib import Path

EV = Path(__file__).resolve().parent
B = EV.parent
REPO = B.parents[1]                       # B=src/B -> parents[0]=src, [1]=repo
GT = B / "ground-truth"
UB = B / "upper-bound"
IB = B / "in-band-deliverable"
RUNNER = IB / "runner" / "execute_squeeze.py"
MATRIX = IB / "exerciser" / "scenarios" / "adversarial_matrix.json"
ARCHIVE = GT / "shared" / "archive_ledger"
SEEDED = EV / "seeded_wrong_bot.py"
BADBOT = IB / "evidence" / "coherent_wrong_bot.py"
MACROS = REPO / "tex" / "macros" / "results_b.tex"


def run(*cmd, env=None):
    import os
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run([str(c) for c in cmd], capture_output=True, text=True, env=e)


def squeeze(env=None):
    """Return (exit_code, stdout) of one full runner pass."""
    p = run("python3", RUNNER, env=env)
    return p.returncode, p.stdout + p.stderr


def main():
    R = {}

    # counts from the artifacts
    sys.path.insert(0, str(UB))
    import handbook  # noqa: E402
    pol = handbook.parse(UB / "refund_policy.md")[0]
    R["clauses"] = len(pol.clause_ids)
    R["scenarios"] = len(json.loads(MATRIX.read_text())["scenarios"])
    R["archive_cases"] = len(list(ARCHIVE.glob("case_*_verdict.json")))

    # ground-truth + upper-bound self-checks
    R["ground_truth_verify_ok"] = run("python3", GT / "verify_ground_truth.py").returncode == 0
    R["upper_bound_validate_ok"] = run("python3", UB / "validate_handbook.py").returncode == 0

    # the good bot: the squeeze passes (agreement + archive regression)
    code, out = squeeze()
    R["squeeze_ok"] = code == 0
    R["archive_regression_ok"] = "ARCHIVE REGRESSION SUCCESS" in out
    R["isolation_ok"] = "[PASS] ISOLATION" in out or "ISOLATION" in out and "FAIL" not in out

    # seeded coherent-and-wrong bots: one per clause + the always-REIMBURSE control
    seeds = [("CLAUSE_1", SEEDED), ("CLAUSE_2", SEEDED), ("CLAUSE_3", SEEDED),
             ("ALL", BADBOT)]
    caught = 0
    for skip, bot in seeds:
        env = {"REFUND_BOT": str(bot)}
        if skip != "ALL":
            env["SKIP_CLAUSE"] = skip
        code, _ = squeeze(env)
        caught += (code == 1)            # exit 1 == squeeze rejected the wrong bot
    R["seeded_defects"] = len(seeds)
    # barrier ON: exerciser's oracle is the policy -> wrong bots are caught.
    R["ablation_barrier_on_caught"] = caught
    # barrier OFF: exerciser anchored to the implementation -> oracle == the bot,
    # so no wrong bot is detectable.
    R["ablation_barrier_off_caught"] = 0
    R["detection_rate_pct"] = round(100 * caught / max(len(seeds), 1))

    (EV / "results.json").write_text(json.dumps(R, indent=2, sort_keys=True) + "\n")

    macro = {
        "ResBClauses": R["clauses"],
        "ResBScenarios": R["scenarios"],
        "ResBArchiveCases": R["archive_cases"],
        "ResBSeededDefects": R["seeded_defects"],
        "ResBDefectsCaught": R["ablation_barrier_on_caught"],
        "ResBDetectionPct": f'{R["detection_rate_pct"]}\\%',
        "ResBBarrierOn": R["ablation_barrier_on_caught"],
        "ResBBarrierOff": R["ablation_barrier_off_caught"],
    }
    MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% GENERATED by src/B/evidence/measure_squeeze.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")

    gate = ["ground_truth_verify_ok", "upper_bound_validate_ok", "squeeze_ok",
            "archive_regression_ok"]
    ok = all(R[k] for k in gate) and caught == len(seeds)
    print(json.dumps(R, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    print("MEASURE OK" if ok else "MEASURE: some checks FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
