#!/usr/bin/env python3
"""O4 (Tier-1-strength) measure + check -> tex/macros/catlog.tex.

Reads claims/category_generation_log.tsv (the per-circle category-generation log) and:
  - VALIDATES the discharge rule: every row's enforcement is on a STRICTLY LATER
    circle than its invention -- min(enforced_circles) > invented_circle. A category
    enforced in the same circle it was coined is relabeling, not later self-application
    (O4); the check exits nonzero (loud-fail) on any violation, so O4 stays partial.
  - EMITS ResLoopCategoriesEnforced = number of categories with a dated later
    enforcement (the strong-O4 count).

This is the artifact that raises O4 from LOGGED-partial to discharged: the static
claims/category_ledger.tsv asserts re-application in one cell; this log dates it.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LOG = REPO / "claims" / "category_generation_log.tsv"
MACROS = REPO / "tex" / "macros" / "catlog.tex"


def rows():
    for line in LOG.read_text().splitlines():
        if not line.startswith("CAT-"):
            continue
        c = line.split("\t")
        yield c[0], int(c[1]), [int(x) for x in c[4].split(";")]


def main():
    enforced = 0
    violations = []
    for cid, invented, enf in rows():
        if min(enf) > invented:
            enforced += 1
        else:
            violations.append(f"{cid}: invented={invented} enforced={enf} (need a later circle)")

    MACROS.write_text(
        "% GENERATED by verify/category_log_measures.py -- do not hand-edit.\n"
        f"\\newcommand{{\\ResLoopCategoriesEnforced}}{{{enforced}}}\n"
    )
    print(f"category-generation log: {enforced} categories enforced on a strictly later circle")
    for v in violations:
        print("  [VIOLATION]", v)
    print("macros ->", MACROS)
    print("O4 (Tier-1-strength):", "DISCHARGED" if not violations else "FAILED (same-circle enforcement)")
    return 0 if not violations else 1


if __name__ == "__main__":
    sys.exit(main())
