#!/usr/bin/env python3
"""Per-instance generated-category over-reach audit (self-improve.md).

The paper generated four categories while squeezing itself; each is asserted as a
general distinction. This is the Gate-S move applied to those categories: does each one
actually GENERALISE across the four object-level instances (A/B/C/D), or does it
over-reach? For each (category, instance) we test an OBJECTIVE artifact marker -- the
operational footprint the category would leave if it applied to that instance. A
category that holds on all four generalises; one that holds on a strict subset
over-reaches and must be CARVED (its scope narrowed), recorded in
claims/category_carveouts.tsv.

Honesty limit (self-improve.md): the markers are operational PROXIES for an
interpretive question, not the interpretive judgment itself. They are clear here
(structural file presence/absence); a genuinely ambiguous fit would route to review,
not be auto-decided. Deterministic; loud-fails only on an uncarved over-reach.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CARVEOUTS = REPO / "claims" / "category_carveouts.tsv"
MACROS = REPO / "tex" / "macros" / "catreach.tex"
INSTANCES = ["A", "B", "C", "D"]


def has(*relpaths):
    return lambda X: all((REPO / p.format(X=X)).exists() for p in relpaths)


# CAT-2 marker: the per-instance constructor of obvious-but-wrong vs correct "forks".
_FORK = {
    "A": "src/A/in-band-deliverable/runner/mutations.py",
    "B": "src/B/in-band-deliverable/exerciser/build_adversarial_matrix.py",
    "C": "src/C/in-band-deliverable/exerciser/build_test_matrix.py",
    "D": "src/D/ground-truth/gate_sentinel.py",
}

CATEGORIES = [
    ("CAT-1", "hard truth vs soft truth",
     # an executable hard lower bound AND a normative soft upper bound both present
     has("src/{X}/ground-truth", "src/{X}/upper-bound")),
    ("CAT-2", "richness = number of separable forks",
     # a constructor of separable wrong-vs-correct readings (forks)
     lambda X: (REPO / _FORK[X]).exists()),
    ("CAT-3", "diversity restores the trial",
     # a random-sampling diversity runner (a varying trial, not a fixed point)
     has("src/{X}/diversity/run_diversity.py")),
    ("CAT-4", "coherent-and-wrong caught only by external challenge",
     # an external-challenge record (internal gates missed, external caught) for THIS
     # instance. Object instances have none; it exists only for the reflexive paper
     # instance (verify/manuscript_defects.tsv). So it is reflexive-only.
     lambda X: False),
]


def carved_ids():
    ids = set()
    if CARVEOUTS.exists():
        for line in CARVEOUTS.read_text().splitlines():
            if line.startswith("CARVE-"):
                ids.add(line.split("\t")[1])
    return ids


def main():
    carves = carved_ids()
    uncarved = 0
    generalises = 0
    print("=== Generated-category over-reach audit (do the paper's categories generalise?) ===")
    for cid, name, marker in CATEGORIES:
        cover = [X for X in INSTANCES if marker(X)]
        if len(cover) == len(INSTANCES):
            generalises += 1
            print(f"  {cid}  GENERALISES  ({name}) -- holds on all {len(INSTANCES)} instances")
        else:
            carved = cid in carves
            tag = "CARVED" if carved else "UNCARVED -> LOUD-FAIL"
            held = ",".join(cover) if cover else "none of the object instances"
            print(f"  {cid}  OVER-REACH [{tag}]  ({name}) -- holds on: {held}")
            if not carved:
                uncarved += 1
    ok = uncarved == 0
    MACROS.parent.mkdir(parents=True, exist_ok=True)
    MACROS.write_text(
        "% GENERATED by verify/category_overreach.py -- do not hand-edit.\n"
        f"\\newcommand{{\\ResCategoryTotal}}{{{len(CATEGORIES)}}}\n"
        f"\\newcommand{{\\ResCategoryGeneralise}}{{{generalises}}}\n"
        f"\\newcommand{{\\ResCategoryOverreach}}{{{len(CATEGORIES) - generalises}}}\n"
        f"\\newcommand{{\\ResCategoryInstances}}{{{len(INSTANCES)}}}\n"
    )
    print(f"\nCategory over-reach audit: {'PASS' if ok else 'FAIL'} "
          f"({uncarved} uncarved over-reach(es)); {generalises}/{len(CATEGORIES)} generalise")
    print("macros ->", MACROS)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
