#!/usr/bin/env python3
"""O3 (closure) check for paper_upper_bound.md (U_self) -> tex/macros/closure.tex.

Executes one full traversal of the reflexive cycle and asserts it RETURNS TO ORIGIN
(closure executed, not asserted):

  method (paper-impl.md) -> manuscript + artifacts -> the reflexive squeeze
  evaluates claims-about-the-method (regenerates the self-record) -> those
  self-counts re-enter the ledger the next circle reads.

Two conditions, both required:
  (a) FIXED POINT  -- re-running verify/reflexive_measures.py leaves
      tex/macros/reflexive.tex byte-identical (the regenerated self-record returns
      to the same state). Because reflexive_measures is deterministic and the file
      is kept current, this rewrite is a no-op -- and that no-op IS the evidence.
  (b) RE-ENTRY     -- the regenerated self-counts ResReflexCiteRows /
      ResReflexResultRows equal the CITE / RESULT row counts in claims/ledger.tsv,
      i.e. the output re-enters the input the next circle reads (the same equality
      Gate C reconciles).

Emits ResLoopClosure = number of ledger-reconciled self-counts that round-trip (2).
Loud-fail: exits nonzero if either condition fails -- then O3 is NOT discharged and
stays CANDIDATE. No net change to the tree (the reflexive.tex rewrite is a no-op).
"""
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LEDGER = REPO / "claims" / "ledger.tsv"
REFLEX = REPO / "tex" / "macros" / "reflexive.tex"
CLOSURE = REPO / "tex" / "macros" / "closure.tex"
REFLEX_GEN = REPO / "verify" / "reflexive_measures.py"


def ledger_counts():
    cite = result = 0
    for line in LEDGER.read_text().splitlines():
        if not re.match(r"^CLM-\d", line):
            continue
        t = line.split("\t")[1]
        if t == "CITE":
            cite += 1
        elif t == "RESULT":
            result += 1
    return cite, result


def macro(name):
    m = re.search(r"\\newcommand\{\\" + name + r"\}\{(\d+)\}", REFLEX.read_text())
    return int(m.group(1)) if m else None


def main():
    # (a) fixed point: regenerate the self-record and confirm it returns to origin.
    before = REFLEX.read_bytes()
    subprocess.run([sys.executable, str(REFLEX_GEN)], capture_output=True)
    after = REFLEX.read_bytes()
    fixed_point = before == after

    # (b) re-entry: regenerated self-counts == the ledger the next circle reads.
    cite, result = ledger_counts()
    cite_ok = macro("ResReflexCiteRows") == cite
    result_ok = macro("ResReflexResultRows") == result
    reconciled = int(cite_ok) + int(result_ok)

    ok = fixed_point and cite_ok and result_ok
    CLOSURE.write_text(
        "% GENERATED by verify/closure_check.py -- do not hand-edit.\n"
        f"\\newcommand{{\\ResLoopClosure}}{{{reconciled}}}\n"
    )

    print(f"closure: fixed_point={fixed_point} cite_ok={cite_ok} result_ok={result_ok} "
          f"ResLoopClosure={reconciled}")
    print("O3 closure:", "EXECUTED (returns to origin)" if ok else "FAILED (not a fixed point / counts diverge)")
    print("macros ->", CLOSURE)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
