#!/usr/bin/env python3
"""Convergence measures -> tex/macros/convergence.tex.

The diversity loops (src/*/diversity) are unbiased Monte-Carlo estimators of a
fixed actor's error rate against a fixed pool, so running more cycles makes the
running mean CONVERGE to that rate (Law of Large Numbers) rather than drift.

This generator makes that recomputable on the refund terrain (B), the one case
whose population error rate is computable EXACTLY -- by enumerating all 100
discussions x 5 characters -- and entirely in the Python standard library (no Coq,
no warehouse). It then runs B's seeded Monte-Carlo to ResConvCycles cycles and
emits the exact rate, the running means at 10 and the full count, and the shrinking
gap. (A/C/D show the same convergence; D needs the kernel, so B is the recomputable
anchor; see 100-iteration-report.md for all four.)
"""
import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MACROS = REPO / "tex" / "macros" / "convergence.tex"
SAMPLE, CYCLES, SEED = 20, 100, 9000

# import the B diversity runner (its helpers; main() is __main__-guarded)
sys.path.insert(0, str(REPO / "src/B/ground-truth"))
spec = importlib.util.spec_from_file_location("bdiv", REPO / "src/B/diversity/run_diversity.py")
B = importlib.util.module_from_spec(spec)
spec.loader.exec_module(B)


def exact_population():
    """Exact error rate over EVERY discussion x character combination."""
    discs, chars = B.load_discussions(), list(B.CHARACTERS)
    err = tot = 0
    for sit, oid, opening in discs:
        for ch in chars:
            cust, order = B.SITUATIONS[sit]
            msgs = [opening] + ([B.CHARACTERS[ch]] if B.CHARACTERS[ch] else [])
            orders = {oid: order}
            intended = B.RP.decide(cust, orders, msgs)
            err += B.bot_realistic(cust, orders, msgs) != intended
            tot += 1
    return err, tot


def monte_carlo():
    """Seeded per-cycle error counts (deterministic, reproducible)."""
    import random
    discs, chars = B.load_discussions(), list(B.CHARACTERS)
    out = []
    for i in range(CYCLES):
        rng = random.Random(SEED + i)
        e = 0
        for _ in range(SAMPLE):
            sit, oid, opening = rng.choice(discs)
            ch = rng.choice(chars)
            cust, order = B.SITUATIONS[sit]
            msgs = [opening] + ([B.CHARACTERS[ch]] if B.CHARACTERS[ch] else [])
            orders = {oid: order}
            intended = B.RP.decide(cust, orders, msgs)
            e += B.bot_realistic(cust, orders, msgs) != intended
        out.append(e)
    return out


def main():
    num, den = exact_population()
    exp20 = SAMPLE * num / den
    xs = monte_carlo()
    mean10 = sum(xs[:10]) / 10
    mean_all = sum(xs) / len(xs)

    def f1(x):
        return f"{x:.1f}"

    macro = {
        "ResConvCycles": CYCLES,
        "ResConvSample": SAMPLE,
        "ResConvBExactNum": num,
        "ResConvBExactDen": den,
        "ResConvBExpected": f1(exp20),
        "ResConvBMeanTen": f1(mean10),
        "ResConvBMeanHundred": f1(mean_all),
        "ResConvBGapTen": f1(abs(mean10 - exp20)),
        "ResConvBGapHundred": f1(abs(mean_all - exp20)),
    }
    lines = ["% GENERATED by verify/convergence_measures.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")
    import json
    print(json.dumps(macro, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
