#!/usr/bin/env python3
"""Evidence--implementation coupling: the n-gram first cut proposed in the
evaluation section, measured on the two executable instances.

H2 predicts that acceptance evidence authored behind a physical context barrier
is *weakly coupled* to the implementation (and catches more seeded defects). This
script computes a concrete, reproducible coupling number for the REAL,
independently authored artifacts of each terrain: the token-bigram Jaccard
overlap between the exerciser's acceptance evidence and the implementer's code.

It measures only the barrier-ON (physically isolated) configuration -- the actual
artifacts. Barrier-off is not "measured": an exerciser that anchors to the
implementation embeds the implementation by construction, so its coupling tends
to the maximum; that extreme, and its zero detection, is the ablation already
reported. The continuous, matched-difficulty, cross-model estimate is future work.
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MACROS = REPO / "tex" / "macros" / "coupling.tex"

# (label, exerciser-evidence paths, implementer-code paths) -- barrier ON (real).
TERRAINS = {
    "A": (
        list((REPO / "src/A/in-band-deliverable/exerciser/tests").glob("validation_matrix*.json")),
        [REPO / "src/A/in-band-deliverable/implementer/src/compute_metric.py"],
    ),
    "B": (
        [REPO / "src/B/in-band-deliverable/exerciser/scenarios/adversarial_matrix.json"],
        [REPO / "src/B/in-band-deliverable/implementer/src/refund_bot_logic.py"],
    ),
    "C": (
        [REPO / "src/C/in-band-deliverable/exerciser/conformance/test_matrix.json"],
        [REPO / "src/C/in-band-deliverable/implementer/src/main.py"],
    ),
}

_TOK = re.compile(r"[a-zA-Z_][a-zA-Z0-9_]*|[0-9][0-9.]*")


def bigrams(paths):
    toks = []
    for p in paths:
        toks += _TOK.findall(p.read_text().lower())
    return set(zip(toks, toks[1:]))


def jaccard(a, b):
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def main():
    macro = {}
    out = {}
    for label, (evid, impl) in TERRAINS.items():
        evid = [p for p in evid if p.exists()]
        impl = [p for p in impl if p.exists()]
        if not evid or not impl:
            print(f"[skip] terrain {label}: artifacts missing")
            continue
        c = jaccard(bigrams(evid), bigrams(impl))
        pct = round(100 * c, 1)
        out[label] = pct
        macro[f"ResCoupling{label}"] = f"{pct}\\%"
        macro[f"ResCoupling{label}val"] = f"{pct}"   # bare number for plots
        print(f"terrain {label}: evidence<->implementation bigram coupling = {pct}% "
              f"(evidence: {[p.name for p in evid]}; impl: {[p.name for p in impl]})")

    MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% GENERATED by verify/coupling_measure.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")
    print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
