#!/usr/bin/env python3
"""Gate S measures -> tex/macros/gates.tex.

Recomputes the headline figures of the skill-consistency monitor (verify/skill_consistency.py)
so the paper's Gate S sentence is macro-bound, not hand-typed. Deterministic: the
oracles and skill stores are committed, so this recomputes byte-identically.

  ResGateSInstances -- base loops monitored (use cases with an adapter)
  ResGateSSkills    -- total learned skills audited across them
  ResGateSFlagged   -- skills flagged as needing a carve-out (a signal the oracle treats
                       as decisive that an ignore-signal skill must not suppress)
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "verify"))
import skill_consistency as GS

MACROS = REPO / "tex" / "macros" / "gates.tex"


def main():
    instances = skills = flagged = 0
    for adapter in GS.ADAPTERS:
        uc, _mode, verdicts = adapter()  # deterministic; oracles are committed
        instances += 1
        skills += len(verdicts)
        flagged += sum(1 for _sig, ok, _d in verdicts if not ok)
    macro = {"ResGateSInstances": instances, "ResGateSSkills": skills, "ResGateSFlagged": flagged}
    MACROS.write_text("% GENERATED by verify/gate_s_measures.py -- do not hand-edit.\n"
                      + "".join(f"\\newcommand{{\\{k}}}{{{macro[k]}}}\n" for k in sorted(macro)))
    import json
    print(json.dumps(macro, indent=2, sort_keys=True)); print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
