#!/usr/bin/env python3
"""Level-up / diversity measures -> tex/macros/levelup.tex.

Aggregates the four diversity experiments (src/{A,B,C,D}/diversity/
diversity_results.json) into the numbers the paper cites, so they recompute rather
than being hand-typed. Each experiment samples a 100-item pool randomly per cycle
against a fixed weak implementer; this emits the pool size, the whole-pool error
baselines, and the per-cycle spread that shows random sampling restores a real,
varying trial.
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MACROS = REPO / "tex" / "macros" / "levelup.tex"
DIV = {u: REPO / f"src/{u}/diversity/diversity_results.json" for u in "ABCD"}


def per_cycle(d):
    for k in ("found_per_cycle", "errors_per_cycle", "caught_per_cycle"):
        if k in d:
            return d[k]
    raise KeyError("no per-cycle list")


def main():
    data = {u: json.loads(p.read_text()) for u, p in DIV.items()}
    poolsize = lambda d: d.get("pool", d.get("discussions"))
    pools = {poolsize(data[u]) for u in "ABCD"}
    samples = {data[u]["sample"] for u in "ABCD"}
    cycles = {data[u]["cycles"] for u in "ABCD"}
    assert pools == {100} and len(samples) == 1 and len(cycles) == 1, (pools, samples, cycles)

    distinct = {u: data[u]["distinct_outcomes"] for u in "ABCD"}
    macro = {
        "ResLevelupTerrains": 4,
        "ResLevelupPool": pools.pop(),
        "ResLevelupSample": samples.pop(),
        "ResLevelupCycles": cycles.pop(),
        "ResLevelupDNotFound": data["D"]["pool_not_found"],     # of 100, == percent
        "ResLevelupADiverge": data["A"]["pool_diverging"],
        "ResLevelupCBlend": data["C"]["pool_blended"],
        "ResLevelupDMin": min(per_cycle(data["D"])),
        "ResLevelupDMax": max(per_cycle(data["D"])),
        "ResLevelupDistinctMax": max(distinct.values()),
    }
    lines = ["% GENERATED by verify/levelup_measures.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")
    print(json.dumps(macro, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
