#!/usr/bin/env python3
"""Perturbation gate (self-improve.md, lesson #3).

Single-anchor verification passes a cherry-pick: a claim can hold on the one passage
quoted or the one seed drawn and still be false in general. This gate perturbs the
anchor and asks whether the claim survives. Two arms (the third -- "check a generated
category on every instance" -- is verify/category_overreach.py):

  CITE / different passage: a comparative or strong citation claim ("outperforms",
    "reduces", "better than", "... vs ...") must trace to a reading record read in
    FULL, not the abstract. Re-opening the source beyond the abstract is the
    perturbation; the manuscript's own literature defects (D1-D3, D7) were exactly
    strong claims an abstract-level read overstated and a full-text read corrected.

  RESULT / different seed: a result that depends on sampling must VARY across seeds
    (its diversity artifact must show >= 2 distinct outcomes over its seeded cycles),
    so the claim reflects a real trial re-run at different seeds, not a single lucky
    draw.

Deterministic: reading records, the ledger, and the committed diversity artifacts are
all fixed. Emits tex/macros/perturb.tex. Loud-fails on a strong claim resting on a
non-FULL record, or a sampling result that does not vary across seeds.
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LEDGER = REPO / "claims" / "ledger.tsv"
RECORDS = REPO / "bib" / "records"
MACROS = REPO / "tex" / "macros" / "perturb.tex"
INSTANCES = ["A", "B", "C", "D"]

# A comparative / strong reading -- the kind that over-reaches from an abstract.
STRONG_RE = re.compile(r"outperform|better than|\breduc|exceed|superior|stronger|"
                       r"more than|improv|beats?\b|\bvs\b", re.I)
# A binding that explicitly scopes itself to the abstract is not asserting the strong
# reading as fact, but we still require the source to have been opened in full.


def cite_rows():
    for line in LEDGER.read_text().splitlines():
        if re.match(r"^CLM-\d", line):
            c = line.split("\t")
            if c[1] == "CITE":
                yield c[0], c[3]  # id, binding (first token = bibkey)


def read_level(bibkey):
    rec = RECORDS / f"{bibkey}.md"
    if not rec.exists():
        return None
    m = re.search(r"read:\s*([A-Z]+)", rec.read_text())
    return m.group(1) if m else None


def cite_arm(bad):
    strong = full = 0
    for cid, binding in cite_rows():
        if not STRONG_RE.search(binding):
            continue
        strong += 1
        bibkey = binding.split()[0]
        lvl = read_level(bibkey)
        if lvl == "FULL":
            full += 1
        else:
            bad.append(f"{cid}: strong/comparative claim on '{bibkey}' read={lvl} "
                       f"(re-open at full text, or scope the claim)")
    print(f"  CITE perturbation: {full}/{strong} strong claims survive a full-text re-open")
    return strong


def seed_arm(bad):
    varying = 0
    for X in INSTANCES:
        art = REPO / "src" / X / "diversity" / "diversity_results.json"
        if not art.exists():
            bad.append(f"{X}: no diversity artifact to perturb"); continue
        d = json.loads(art.read_text())
        distinct = d.get("distinct_outcomes", 0)
        if distinct >= 2:
            varying += 1
        else:
            bad.append(f"{X}: diversity result does not vary across seeds "
                       f"(distinct_outcomes={distinct})")
    print(f"  RESULT perturbation: {varying}/{len(INSTANCES)} instances vary across seeds")
    return varying


def main():
    print("=== Perturbation gate (does the claim survive a perturbed anchor?) ===")
    bad = []
    strong = cite_arm(bad)
    seeds = seed_arm(bad)
    MACROS.parent.mkdir(parents=True, exist_ok=True)
    MACROS.write_text(
        "% GENERATED by verify/perturbation.py -- do not hand-edit.\n"
        f"\\newcommand{{\\ResPerturbStrongCites}}{{{strong}}}\n"
        f"\\newcommand{{\\ResPerturbSeedInstances}}{{{seeds}}}\n"
    )
    ok = not bad
    print(f"\nPerturbation gate: {'PASS' if ok else 'FAIL'} "
          f"({strong} strong cites re-opened, {seeds} seed-varying instances)")
    for b in bad:
        print("  [FAIL]", b)
    print("macros ->", MACROS)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
