#!/usr/bin/env python3
"""Reflexive measures: this paper, produced as a squeeze loop.

Counts the loop's own self-application artifacts from the repository and emits
tex/macros/reflexive.tex, so the reflexive case study's numbers recompute just
like every other number in the paper (no hand-typed figures).

Sources (all committed):
  verify/manuscript_defects.tsv  defects the gates caught in the paper's own claims
  bib/records/*.md               reading records (and their access level)
  claims/ledger.tsv              the claim ledger (CITE / RESULT rows)
  docs/*-paper-spec-*.md         per-circle plan docs
  docs/*-paper-gap-*.md          gap (divergence) docs
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RECORDS = REPO / "bib" / "records"
LEDGER = REPO / "claims" / "ledger.tsv"
DEFECTS = REPO / "verify" / "manuscript_defects.tsv"
DOCS = REPO / "docs"
MACROS = REPO / "tex" / "macros" / "reflexive.tex"


def count_defects():
    total = lit = evid = 0
    for line in DEFECTS.read_text().splitlines():
        if not line.startswith("D"):          # skip header + comments
            continue
        parts = line.split("\t")
        total += 1
        if parts[1] == "literature":
            lit += 1
        elif parts[1] == "evidence":
            evid += 1
    return total, lit, evid


def count_records():
    files = sorted(RECORDS.glob("*.md"))
    full = 0
    for f in files:
        txt = f.read_text()
        # count as FULL only if an actual value was filled (not the unfilled
        # "read: FULL | PARTIAL | SECONDARY" template line)
        if re.search(r"read:\s*FULL\b", txt) and "FULL | PARTIAL" not in txt:
            full += 1
    return len(files), full


def count_terrains():
    """Executable instances the loop produced and verified (four: A and D both
    on the transcription terrain, B authored authority, C split planes)."""
    return sum((REPO / "src" / t / "evidence" / "results.json").exists()
               for t in ("A", "B", "C", "D"))


def count_ledger():
    cite = result = 0
    for line in LEDGER.read_text().splitlines():
        if not re.match(r"^CLM-\d", line):
            continue
        t = line.split("\t")[1]
        if t == "CITE":
            cite += 1
        elif t == "RESULT":
            result += 1
    return cite, result


def main():
    d_total, d_lit, d_evid = count_defects()
    rec_total, rec_full = count_records()
    cite, result = count_ledger()
    spec_docs = len(list(DOCS.glob("*-paper-spec-*.md")))
    gap_docs = len(list(DOCS.glob("*-paper-gap-*.md")))

    macro = {
        "ResReflexTerrains": count_terrains(),
        "ResReflexDefects": d_total,
        "ResReflexDefectsLit": d_lit,
        "ResReflexDefectsEvid": d_evid,
        "ResReflexRecords": rec_total,
        "ResReflexRecordsFull": rec_full,
        "ResReflexCiteRows": cite,
        "ResReflexResultRows": result,
        "ResReflexSpecDocs": spec_docs,
        "ResReflexGapDocs": gap_docs,
    }
    MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% GENERATED by verify/reflexive_measures.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")

    print(json.dumps(macro, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
