#!/usr/bin/env python3
"""Live self-model (O1 + O5) -> claims/self_model.json + tex/macros/selfmodel.tex.

The loop's DERIVED model of its own discharge state. Per paper_upper_bound.md the
self-model must be (a) derived from the live repo state, not hand-authored fiction;
(b) consulted to choose the next obligation (`next_target`); (c) updated across
circles in a way that redirects the loop. This script computes (a) and (c)'s record;
verify/self_model_check.py asserts (b) and the redirect (the O1+O5 discharge witness).

Derivation (idempotent -- re-running reproduces the JSON byte-identically):
  - clause discharge  <- presence of the discharging artifact in the repo
  - history           <- the `TARGET:` header of each docs/*-paper-spec-*.md
  - next_target       <- the highest-priority still-open gap (a pure function of the
                         clause statuses), NOT hand-set (the anti-gaming guard)
"""
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"
MODEL = REPO / "claims" / "self_model.json"
MACROS = REPO / "tex" / "macros" / "selfmodel.tex"

# A clause is discharged iff its discharging artifact exists.
ARTIFACT = {
    "O2": "claims/level_crossings.tsv",
    "O3": "verify/closure_check.py",
    "O4": "claims/category_generation_log.tsv",
}


def clause_status():
    st = {c: ("discharged" if (REPO / rel).exists() else "partial")
          for c, rel in ARTIFACT.items()}
    # O1 and O5 are discharged together by the live self-model: the model artifact
    # plus its discharge check both present.
    live = MODEL.exists() and (REPO / "verify" / "self_model_check.py").exists()
    st["O1"] = st["O5"] = "discharged" if live else "partial"
    return st


def history():
    h = []
    for f in sorted(DOCS.glob("*-paper-spec-*.md")):
        m = re.search(r"-paper-spec-(\d+)\.md$", f.name)
        if not m:
            continue
        t = re.search(r"^TARGET:\s*(\S+)", f.read_text(), re.M)
        if t:
            h.append({"circle": int(m.group(1)), "target": t.group(1)})
    return sorted(h, key=lambda e: e["circle"])


def next_target(st):
    """The top open gap -- a pure function of clause status (not hand-set)."""
    if st["O4"] != "discharged":
        return "G-O4"
    if st["O1"] != "discharged" or st["O5"] != "discharged":
        return "G-O1O5"
    return "G-tier-review"  # all O1-O5 discharged; remaining work is the §7 tier review


def build():
    st = clause_status()
    h = history()
    nt = next_target(st)
    return {
        "circle": h[-1]["circle"] if h else 0,
        "derived": True,
        "clauses": st,
        "history": h,
        "next_target": nt,
    }


def main():
    model = build()
    MODEL.write_text(json.dumps(model, indent=2, sort_keys=True) + "\n")
    MACROS.write_text(
        "% GENERATED by verify/self_model.py -- do not hand-edit.\n"
        f"\\newcommand{{\\ResSelfModelCircle}}{{{model['circle']}}}\n"
        f"\\newcommand{{\\ResSelfModelUpdates}}{{{len(model['history'])}}}\n"
    )
    print(json.dumps(model, indent=2, sort_keys=True))
    print("model ->", MODEL, "| macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
