#!/usr/bin/env python3
"""Skill-accumulation measures: the squeeze forces new-concept creation in the
squeezed agent.

Reads the four committed end-to-end skill-accumulation results (one per
executable instance) and emits tex/macros/skill.tex, so the evaluation section's
skill numbers recompute like every other number in the paper -- no hand-typed
figures. Needs no kernel and no model: it reads the committed JSON the four
skill loops wrote (src/{A,B,C,D}/skill/skill_enrichment_results.json).

Honest scope: the deciding agents are deterministic programmatic learners over
fixed catalogs (docs/skill-accumulation-design.md, Rule 1: only the decider
learns), NOT live LLMs. The measured claim is that the squeeze's
caught -> consolidate mechanism enriches skill and is causal; the per-model error
gradient stays OPN (CLM-070).
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MACROS = REPO / "tex" / "macros" / "skill.tex"

# (instance, json path, final-skill field, first-window field, last-window field)
INSTANCES = [
    ("A", "errors_first_window_mean", "errors_last_window_mean"),
    ("B", "errors_first_window_mean", "errors_last_window_mean"),
    ("C", "blends_first_window_mean", "blends_last_window_mean"),
    ("D", "solvable_miss_first_window_mean", "solvable_miss_last_window_mean"),
]


def load(inst):
    p = REPO / "src" / inst / "skill" / "skill_enrichment_results.json"
    return json.loads(p.read_text())


def skill_count(d):
    """Final skill size, however the instance named the field."""
    if "final_skill_size" in d:
        return d["final_skill_size"]
    return len(d["final_skill"])


def fmt(x):
    """Trim a float to its shortest exact decimal (2.9 not 2.90, 0 not 0.0)."""
    return f"{x:g}"


def main():
    data = {inst: load(inst) for inst, _, _ in INSTANCES}

    learned = sum(skill_count(data[i]) for i, _, _ in INSTANCES)
    cycles = data["B"]["cycles"]
    max_last = max(data[i][last] for i, _, last in INSTANCES)

    macro = {
        "ResSkillInstances": len(INSTANCES),
        "ResSkillCycles": cycles,
        "ResSkillLearned": learned,
        "ResSkillBClasses": skill_count(data["B"]),
        "ResSkillBErrFirst": fmt(data["B"]["errors_first_window_mean"]),
        "ResSkillMaxSolvableLast": fmt(max_last),
        "ResSkillDTactics": skill_count(data["D"]),
        "ResSkillDWall": data["D"]["conceptual_leap_wall"],
        "ResSkillDPool": 100,
    }

    MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% GENERATED by verify/skill_measures.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")

    print(json.dumps(macro, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
