#!/usr/bin/env python3
"""Strange-loop discharge measures -> tex/macros/strangeloop.tex.

Assembles the evidence the paper cites for the U_self (paper_upper_bound.md)
strange-loop claim, so the numbers recompute:
  - O4 categories generated under self-application   <- claims/category_ledger.tsv
  - O2 level-crossings (a self-representation forced a substrate change)
                                                     <- claims/level_crossings.tsv
  - O5 persistence (iterations of the self-applying loop)
                                                     <- docs/specs/*-paper-spec-*.md
The admissible TIER is the disposition recorded in paper_upper_bound.md §8 (Tier 2:
O2 and O3 DISCHARGED -- claims/level_crossings.tsv + verify/closure_check.py; O1/O5
partial, no live self-model; O4 logged but not Tier-1-strong). It is a documented
judgment, not a computed value; bump it only when O1, O4, and O5 are discharged.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MACROS = REPO / "tex" / "macros" / "strangeloop.tex"
CATS = REPO / "claims" / "category_ledger.tsv"
LXLOG = REPO / "claims" / "level_crossings.tsv"
DOCS = REPO / "docs"

TIER = 2  # paper_upper_bound.md §8 disposition (loud-fail: round down; never Tier 0)


def main():
    n_cat = sum(1 for l in CATS.read_text().splitlines() if l.startswith("CAT-"))
    # O2: only genuine self-representation -> substrate-change chains
    # (claims/level_crossings.tsv), NOT the full manuscript-defect audit.
    n_lx = sum(1 for l in LXLOG.read_text().splitlines() if l.startswith("LX-"))

    # persistence (O5) is the loop's circle count -- reuse the canonical
    # ResReflexSpecDocs from reflexive.tex rather than re-counting it here.
    macro = {
        "ResLoopTier": TIER,
        "ResLoopCategories": n_cat,
        "ResLoopLevelCrossings": n_lx,
    }
    lines = ["% GENERATED by verify/strange_loop.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")
    import json
    print(json.dumps(macro, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    return 0


if __name__ == "__main__":
    sys.exit(main())
