#!/usr/bin/env python3
"""Synthesis across the executable instances.

Aggregates the per-instance evidence (src/{A,B,C,D}/evidence/results.json) into the
cross-instance numbers the paper's synthesis cites, so the totals recompute rather
than being hand-summed. FOUR executable instances over THREE terrain archetypes
(A and D both on the transcription terrain): same pattern, one aggregate result.
D's results.json uses the Rocq-flavoured key names, mapped below.
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MACROS = REPO / "tex" / "macros" / "synthesis.tex"

ARCHETYPES = 3  # the taxonomy is three terrains; A and D are both transcription
TERRAINS = {
    "A": REPO / "src/A/evidence/results.json",
    "B": REPO / "src/B/evidence/results.json",
    "C": REPO / "src/C/evidence/results.json",
    "D": REPO / "src/D/evidence/results.json",
}


def main():
    seeded = on = off = 0
    per = {}
    for label, path in TERRAINS.items():
        R = json.loads(path.read_text())
        s = R.get("seeded_defects", R.get("seeded_mutations"))
        o = R.get("ablation_barrier_on_caught", R.get("defects_caught"))
        f = R.get("ablation_barrier_off_caught", R.get("ablation_barrier_off_catchable"))
        per[label] = (s, o, f)
        seeded += s
        on += o
        off += f
        print(f"terrain {label}: seeded={s} caught_on={o} caught_off={f}")

    macro = {
        "ResNTerrains": len(TERRAINS),       # executable instances (now four)
        "ResNArchetypes": ARCHETYPES,        # terrain archetypes (three)
        "ResAllSeeded": seeded,
        "ResAllCaught": on,
        "ResAllBarrierOff": off,
    }
    MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% GENERATED by verify/synthesis.py -- do not hand-edit."]
    for k in sorted(macro):
        lines.append(f"\\newcommand{{\\{k}}}{{{macro[k]}}}")
    MACROS.write_text("\n".join(lines) + "\n")

    print(json.dumps(macro, indent=2, sort_keys=True))
    print("macros ->", MACROS)
    # sanity: with the barrier on every seeded defect is caught; with it off none.
    return 0 if (on == seeded and off == 0) else 1


if __name__ == "__main__":
    sys.exit(main())
