"""Shared helpers for the reflexive instance (src/paper).

src/paper is the paper itself, treated as a squeeze. Unlike src/A..D it is NOT a
sandboxed experiment: its lower bound (the executable evidence + the build), its
upper bound (the read literature + the paper-spec), and its in-band deliverable
(the manuscript) are the REAL repository artifacts, so these scripts read tex/,
bib/, claims/, verify/, eval/ at the repo root and may regenerate committed
macros. That is the point -- the method is applied to its own paper.
"""

import re
import subprocess
from pathlib import Path


def repo_root() -> Path:
    """Walk up until we find the repo (the dir holding tex/paper.tex)."""
    d = Path(__file__).resolve()
    for p in [d, *d.parents]:
        if (p / "tex" / "paper.tex").exists():
            return p
    raise SystemExit("cannot locate repo root (tex/paper.tex not found)")


REPO = repo_root()
PAPER = REPO / "tex" / "paper.tex"
BIB = REPO / "tex" / "references.bib"
RECORDS = REPO / "bib" / "records"
LEDGER = REPO / "claims" / "ledger.tsv"
REFLEX = REPO / "tex" / "macros" / "reflexive.tex"

# The executable substrate of the manuscript: every committed macro file is
# regenerated by exactly one of these (cwd, script) generators. This is the
# single source of truth for "every number recomputes". (src/D is not yet wired
# into the paper; it joins this list when a circle brings Use Case D in.)
GENERATORS = [
    ("src/A/evidence", "measure_squeeze.py"),
    ("src/B/evidence", "measure_squeeze.py"),
    ("src/C/evidence", "measure_squeeze.py"),
    ("verify", "results_d.py"),
    ("verify", "coupling_measure.py"),
    ("verify", "synthesis.py"),
    ("verify", "eval_protocol.py"),
    ("eval/pilot", "score.py"),
    ("eval/pilot2", "score.py"),
    ("eval/pilot3", "score.py"),
    ("eval/study", "score.py"),
    ("eval/swebench", "run_protocol.py"),
    ("verify", "levelup_measures.py"),
    ("verify", "strange_loop.py"),
    ("verify", "convergence_measures.py"),
    ("verify", "skill_measures.py"),
    ("verify", "reflexive_measures.py"),
    ("verify", "category_log_measures.py"),
    ("verify", "self_model.py"),
    ("verify", "gate_s_measures.py"),
    ("verify", "category_overreach.py"),
    ("verify", "perturbation.py"),
    ("verify", "flag_rate.py"),
    ("verify", "closure_check.py"),
]


def run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd or REPO, capture_output=True, text=True)


def cite_keys() -> set:
    txt = PAPER.read_text()
    keys = set()
    for m in re.finditer(r"\\cite[a-z]*\{([^}]+)\}", txt):
        for k in m.group(1).split(","):
            keys.add(k.strip())
    return keys


def bib_keys() -> set:
    return set(re.findall(r"^@[a-zA-Z]+\{([^,]+),", BIB.read_text(), re.M))


def record_keys() -> set:
    return {p.stem for p in RECORDS.glob("*.md")}


def ledger_rows(kind: str) -> list:
    """Return [(clm, bibkey-or-binding, full-binding)] for CITE or RESULT rows."""
    rows = []
    for ln in LEDGER.read_text().splitlines():
        if ln.startswith("#") or not ln.strip():
            continue
        f = ln.split("\t")
        if len(f) >= 4 and f[1] == kind:
            rows.append((f[0], f[3].split()[0], f[3]))
    return rows


def reflex_macro(name: str):
    m = re.search(r"\\newcommand\{\\" + name + r"\}\{([^}]*)\}", REFLEX.read_text())
    return m.group(1) if m else None


class Gate:
    """Tiny pass/fail reporter shared by the layer scripts (mirrors src/A..D)."""

    def __init__(self):
        self.ok = True

    def check(self, label, cond, detail=""):
        tag = "[PASS]" if cond else "[FAIL]"
        if not cond:
            self.ok = False
        print(f"{tag} {label}" + (f" -- {detail}" if detail else ""))
        return cond

    def skip(self, label, detail=""):
        print(f"[SKIP] {label}" + (f" -- {detail}" if detail else ""))
